### ISSUE TITLE
Refactor pass/fail file paths

### ISSUE THREAD

**Issue by rickhousley** [rickhousley/SSW-Agile-GEDCOM#1]
Right now every pass fail file has a base url of "acceptance_files/pass/" or "acceptance_files/fail/" this should be stored in a constant or saved in a config

**Comment by bryangardner** [comment]
I'll refactor this @rickhousley

**Comment by rickhousley** [comment]
This can be further refactored to just a file name. Pass and fail file names are the same; just the directories are different

**Comment by bryangardner** [comment]
alright, I agree. I'll fix
